### ISSUE TITLE
Using both `===` and `!==` in `router.js`

### ISSUE THREAD

**Issue by yvonne-liu** [facn2/ApolloXII#35]
Okay, I know they're the same, but it's probably best practice to stick to one or the other: 

![screen shot 2017-07-27 at 10 25 14 am](https://user-images.githubusercontent.com/22013117/28658866-e9197c38-72b5-11e7-9c1c-bdcc12339888.png)

**Comment by rinoma** [comment]
This is necessary.

**Comment by yvonne-liu** [comment]
OMG, you're totally right. I had a brain fart and confused myself :grin::flushed:
